# Site settings
title: "Размышления наедине с собой"
author: "Genrih Grigoryan"
description: "Подъем в гору без страховки."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: ""
colophon: ""

baseurl: ""
url: "http://blog.genrihgrigoryan.com"

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
instagram_username: hugo.sereno.ferreira
500px_username: hugoserenoferreira

google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
